app: 
  name: short-app
  image: antonlarichev/short-app
  version: v1.4
  replicas: 1
  components: frontend
  port: 80
  limits: 
    memory: "128Mi"
    cpu: "100m"

api: 
  name: short-api
  image: antonlarichev/short-api
  version: v1.0
  replicas: 1
  components: backend
  port: 3000
  limits: 
    memory: "500Mi"
    cpu: "200m" 
  envs: 
    - DATABASE_URL   

database: 
  user: demo
  password: demo
  db: demo

postgres: 
  name: postgres
  image: postgres
  version: v16.0
  components: postgres
  port: 5432
  limits: 
    memory: "500Mi"
    cpu: "300m" 
  envs: 
    - POSTGRES_DB
    - POSTGRES_USER
    - POSTGRES_PASSWORD
  

env: production
value: 
  requirements:
    limits: 
      memory: "128Mi"
      cpu: "100m"

users: 
  - Ivan
  - Vova

users1:
  - name: Ivan
    role: admin
  - name: Vova
    role: admin2
