apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc

spec:
  resources: # какие ресурсы мы запрашиваем 
    requests:
      storage: 1Gi

  accessModes: # режимы работы с внешними инстансами
    - ReadWriteOnce
