apiVersion: v1
kind: Pod
metadata: 
  name: short-app
  labels:
    components: frontend

spec: # спецификация
  containers:
    - name: short-app
      image: antonlarichev/short-app
      ports: 
        - containerPort: 80
      resources: 
        limits: # ограничения на работу контейнера по памяти и процессору 
          memory: "128Mi" # 128 мегабайт максимум
          cpu: "500m" # 1000m - загрузка одного процессора, те сейчас оно загрузит наполовину